name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore --configfile nuget.org.config

      - name: Build
        run: dotnet build --no-restore --no-incremental

      - name: Test
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory coverage

      - name: Upload coverage to Codecov
        if: matrix.os == 'windows-latest'
        uses: codecov/codecov-action@v4
        with:
          directory: coverage
          fail_ci_if_error: false
